project_id = "gaytlowwebmmycswnshu"

[functions.welcome-email]
enabled = true
verify_jwt = true
import_map = "./functions/welcome-email/deno.json"
entrypoint = "./functions/welcome-email/index.ts"

[functions.save-subscription]
enabled = true
verify_jwt = true

[functions.send-scheduled-notifications]
enabled = true
verify_jwt = false
# Le cron est configuré via pg_cron dans la migration 06_cron_notifications.sql

[functions.send-weekly-summary]
enabled = true
verify_jwt = false
# Le cron est configuré via pg_cron dans la migration 07_cron_weekly_summary.sql
